spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: qwerty
#Defualt value = spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
  liquibase:
    change-log: classpath:db/changelog/master.yaml

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

